parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaVersion: 2022
  project: ./tsconfig.base.json

ignorePatterns:
  - vite.config.ts

extends:
  - '@astahmer/eslint-config-ts'

rules:
  import/exports-last: error
  import/first: error
  import/no-duplicates: error
  import/order: off

  simple-import-sort/imports: error
  simple-import-sort/exports: error

  unused-imports/no-unused-imports: error
  quotes: 'single'
