version: '3'

networks:
  corp:
    driver: bridge

services:
  api0:
    container_name: api0
    networks:
      - corp
    build: ./packages/server
    ports:
      - '9001:9000'
    depends_on:
      - database
  api1:
    container_name: api1
    networks:
      - corp
    build: ./packages/server
    ports:
      - '9002:9000'
