import { z } from 'zod';

export const schema = z.object({
  command: z.string(),
  results: z.object({
    list: z.array(
      z.object({
        tournoi: z.object({
          millesime: z.number(),
          libelle: z.string(),
          publicationProg: z.boolean(),
          tmc: z.boolean(),
          tarifAdulteChampionnat: z.number(),
          type: z.string(),
          ageReel: z.boolean(),
          naturesTerrains: z.array(
            z.object({
              code: z.string(),
              libelle: z.string(),
              valide: z.boolean(),
              categorieJeu: z.object({
                code: z.string(),
                libelle: z.string(),
                valide: z.boolean(),
              }),
            })
          ),
          id: z.number(),
          idsArbitres: z.array(z.unknown()),
          tarifJeuneChampionnat: z.number(),
          international: z.boolean(),
          inscriptionEnLigne: z.boolean(),
          categorieTournoi: z.object({
            code: z.string(),
            codeTaxe: z.string(),
            libelle: z.string(),
            niveauHierarchique: z.string(),
            valide: z.boolean(),
          }),
          prixLot: z.number(),
          paiementEnLigne: z.boolean(),
          reductionAdherentJeune: z.number(),
          reductionAdherentAdulte: z.number(),
          paiementEnLigneObligatoire: z.boolean(),
          villeEngagement: z.string().optional(),
          senior: z.boolean(),
          veteran: z.boolean(),
          inscriptionEnLigneEnCours: z.boolean(),
          avecResultatPublie: z.boolean(),
          dateOuvertureInscriptionEnLigne: z.string().optional(),
          code: z.string(),
          categorieAge: z.object({
            ageJoueurMin: z.number(),
            ageMin: z.number(),
            ageJoueurMax: z.number(),
            ageRechercheMax: z.number(),
            categoriesAgeTypePratique: z.array(
              z.object({
                createTime: z.string(),
                id: z.object({
                  typePratique: z.string(),
                  idCategorieAge: z.number(),
                }),
              })
            ),
            ageMax: z.number(),
            libelle: z.string(),
            id: z.number(),
            valide: z.boolean(),
            ageReel: z.boolean(),
            ageRechercheMin: z.number(),
            homologable: z.boolean(),
          }),
          codeComite: z.string(),
          installations: z.array(
            z.object({
              ville: z.string(),
              lng: z.number().optional(),
              surfaces: z.array(
                z.object({
                  code: z.string(),
                  libelle: z.string(),
                  eclaire: z.boolean(),
                  nombre: z.number(),
                })
              ),
              vestiaires: z.boolean(),
              codePostal: z.string(),
              adresse1: z.string().optional(),
              nom: z.string().nullable(),
              adresse2: z.string().optional(),
              lat: z.number().optional(),
              clubHouse: z.boolean(),
            })
          ),
          reductionEpreuveSupplementaireJeune: z.number(),
          reductionEpreuveSupplementaireAdulte: z.number(),
          publicationResultat: z.boolean(),
          nomComite: z.string(),
          naturesEpreuves: z.array(
            z.object({
              code: z.string(),
              libelle: z.string(),
              sexe: z.string(),
              valide: z.boolean(),
            })
          ),
          jeune: z.boolean(),
          courrielEngagement: z.string().optional(),
          nomClub: z.string(),
          installation: z.object({
            ville: z.string(),
            lng: z.number().optional(),
            surfaces: z.array(z.unknown()),
            vestiaires: z.boolean(),
            codePostal: z.string(),
            adresse1: z.string().optional(),
            nom: z.string().nullable(),
            adresse2: z.string().optional(),
            lat: z.number().optional(),
            clubHouse: z.boolean(),
          }),
          categorieAgeMax: z.object({
            ageJoueurMin: z.number(),
            ageMin: z.number(),
            ageJoueurMax: z.number(),
            ageRechercheMax: z.number(),
            categoriesAgeTypePratique: z.array(
              z.object({
                createTime: z.string(),
                id: z.object({
                  typePratique: z.string(),
                  idCategorieAge: z.number(),
                }),
              })
            ),
            ageMax: z.number(),
            libelle: z.string(),
            id: z.number(),
            valide: z.boolean(),
            ageReel: z.boolean(),
            ageRechercheMin: z.number(),
            homologable: z.boolean(),
          }),
          tournoiInterne: z.boolean(),
          nomLigue: z.string(),
          distanceEnMetres: z.string(),
          familleTournoi: z.array(z.unknown()),
          nomEngagement: z.string().optional(),
          codeLigue: z.string(),
          modeleDeBalle: z
            .object({
              libelle: z.string(),
              marqueDeBalle: z.object({
                id: z.number(),
                valide: z.boolean(),
                marque: z.string(),
              }),
              id: z.number(),
              valide: z.boolean(),
              homologue: z.boolean(),
            })
            .optional(),
          jugeArbitre: z.object({
            idCrm: z.number(),
            id: z.number().nullable(),
            nom: z.string().nullable(),
            prenom: z.string().nullable(),
          }),
          epreuves: z.array(
            z.union([
              z.object({
                inscriptionEnLigneEnCours: z.boolean(),
                categorieAge: z.object({
                  ageJoueurMin: z.number(),
                  ageMin: z.number(),
                  ageJoueurMax: z.number(),
                  ageRechercheMax: z.number(),
                  categoriesAgeTypePratique: z.array(
                    z.object({
                      createTime: z.string(),
                      id: z.object({
                        typePratique: z.string(),
                        idCategorieAge: z.number(),
                      }),
                    })
                  ),
                  ageMax: z.number(),
                  libelle: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  ageReel: z.boolean(),
                  ageRechercheMin: z.number(),
                  homologable: z.boolean(),
                }),
                classementHaut: z.object({
                  nature: z.string(),
                  libelle: z.string(),
                  serie: z.object({
                    code: z.string(),
                    libelle: z.string(),
                    valide: z.boolean(),
                  }),
                  sexe: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  poidsDouble: z.number(),
                  echelon: z.number(),
                }),
                nombreDecoupagesPublies: z.number(),
                libelle: z.string(),
                participationAgeReel: z.boolean(),
                decoupages: z
                  .array(
                    z.union([
                      z.object({
                        classementBas: z.object({
                          nature: z.string(),
                          libelle: z.string(),
                          serie: z.object({
                            code: z.string(),
                            libelle: z.string(),
                            valide: z.boolean(),
                          }),
                          sexe: z.string(),
                          id: z.number(),
                          valide: z.boolean(),
                          poidsDouble: z.number(),
                          echelon: z.number(),
                        }),
                        rangProgression: z.number(),
                        classementHaut: z.object({
                          nature: z.string(),
                          libelle: z.string(),
                          serie: z.object({
                            code: z.string(),
                            libelle: z.string(),
                            valide: z.boolean(),
                          }),
                          sexe: z.string(),
                          id: z.number(),
                          valide: z.boolean(),
                          poidsDouble: z.number(),
                          echelon: z.number(),
                        }),
                        libelle: z.string(),
                        id: z.number(),
                        type: z.string(),
                        statut: z.object({
                          libelle: z.string(),
                          id: z.number(),
                        }),
                        publicationResultat: z.boolean(),
                      }),
                      z.object({
                        classementBas: z.object({
                          nature: z.string(),
                          libelle: z.string(),
                          serie: z.object({
                            code: z.string(),
                            libelle: z.string(),
                            valide: z.boolean(),
                          }),
                          sexe: z.string(),
                          id: z.number(),
                          valide: z.boolean(),
                          poidsDouble: z.number(),
                          echelon: z.number(),
                        }),
                        rangProgression: z.number(),
                        classementHaut: z.object({
                          nature: z.string(),
                          libelle: z.string(),
                          serie: z.object({
                            code: z.string(),
                            libelle: z.string(),
                            valide: z.boolean(),
                          }),
                          sexe: z.string(),
                          id: z.number(),
                          valide: z.boolean(),
                          poidsDouble: z.number(),
                          echelon: z.number(),
                        }),
                        libelle: z.string(),
                        id: z.number(),
                        type: z.string(),
                        publicationResultat: z.boolean(),
                      }),
                    ])
                  )
                  .optional(),
                clotureInscriptionSansPreavis: z.boolean(),
                type: z.string(),
                publicationResultat: z.boolean(),
                tarifJeune: z.number(),
                categorieAgeMax: z.object({
                  ageJoueurMin: z.number(),
                  ageMin: z.number(),
                  ageJoueurMax: z.number(),
                  ageRechercheMax: z.number(),
                  categoriesAgeTypePratique: z.array(
                    z.object({
                      createTime: z.string(),
                      id: z.object({
                        typePratique: z.string(),
                        idCategorieAge: z.number(),
                      }),
                    })
                  ),
                  ageMax: z.number(),
                  libelle: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  ageReel: z.boolean(),
                  ageRechercheMin: z.number(),
                  homologable: z.boolean(),
                }),
                id: z.number(),
                natureEpreuve: z.object({
                  code: z.string(),
                  libelle: z.string(),
                  sexe: z.string(),
                  valide: z.boolean(),
                }),
                inscriptionEnLigne: z.boolean(),
                fillesAutorisees: z.boolean(),
                formatMatch: z.object({
                  code: z.string(),
                  classementMax: z.object({
                    nature: z.string(),
                    libelle: z.string(),
                    serie: z.object({
                      code: z.string(),
                      libelle: z.string(),
                      valide: z.boolean(),
                    }),
                    sexe: z.string(),
                    id: z.number(),
                    valide: z.boolean(),
                    poidsDouble: z.number(),
                    echelon: z.number(),
                  }),
                  ageMax: z.number(),
                  nombreSets: z.number(),
                  double: z.boolean(),
                  libelle: z.string(),
                  simple: z.boolean(),
                  valide: z.boolean(),
                  superJeuDecisif: z.boolean(),
                  ageMin: z.number(),
                  coefficient: z.number(),
                  duree: z.number(),
                  classementMin: z.object({
                    nature: z.string(),
                    libelle: z.string(),
                    serie: z.object({
                      code: z.string(),
                      libelle: z.string(),
                      valide: z.boolean(),
                    }),
                    sexe: z.string(),
                    id: z.number(),
                    valide: z.boolean(),
                    poidsDouble: z.number(),
                    echelon: z.number(),
                  }),
                  millesimeDebutValidite: z.number(),
                }),
                tarifAdulte: z.number(),
                dateProgrammation: z.string().optional(),
                classementBas: z.object({
                  nature: z.string(),
                  libelle: z.string(),
                  serie: z.object({
                    code: z.string(),
                    libelle: z.string(),
                    valide: z.boolean(),
                  }),
                  sexe: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  poidsDouble: z.number(),
                  echelon: z.number(),
                }),
                tarifsSpecifiques: z.array(z.unknown()),
                homologuee: z.boolean(),
                dateDebut: z.string(),
                dateFin: z.string(),
                borneAnneesNaissance: z.object({
                  min: z.number(),
                  max: z.number(),
                }),
                open: z.boolean(),
                statut: z.object({ libelle: z.string(), id: z.number() }),
              }),
              z.object({
                inscriptionEnLigneEnCours: z.boolean(),
                categorieAge: z.object({
                  ageJoueurMin: z.number(),
                  ageMin: z.number(),
                  ageJoueurMax: z.number(),
                  ageRechercheMax: z.number(),
                  categoriesAgeTypePratique: z.array(
                    z.object({
                      createTime: z.string(),
                      id: z.object({
                        typePratique: z.string(),
                        idCategorieAge: z.number(),
                      }),
                    })
                  ),
                  ageMax: z.number(),
                  libelle: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  ageReel: z.boolean(),
                  ageRechercheMin: z.number(),
                  homologable: z.boolean(),
                }),
                classementHaut: z.object({
                  nature: z.string(),
                  libelle: z.string(),
                  serie: z.object({
                    code: z.string(),
                    libelle: z.string(),
                    valide: z.boolean(),
                  }),
                  sexe: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  poidsDouble: z.number(),
                  echelon: z.number(),
                }),
                nombreDecoupagesPublies: z.number(),
                libelle: z.string(),
                participationAgeReel: z.boolean(),
                decoupages: z
                  .array(
                    z.union([
                      z.object({
                        classementBas: z.object({
                          nature: z.string(),
                          libelle: z.string(),
                          serie: z.object({
                            code: z.string(),
                            libelle: z.string(),
                            valide: z.boolean(),
                          }),
                          sexe: z.string(),
                          id: z.number(),
                          valide: z.boolean(),
                          poidsDouble: z.number(),
                          echelon: z.number(),
                        }),
                        rangProgression: z.number(),
                        classementHaut: z.object({
                          nature: z.string(),
                          libelle: z.string(),
                          serie: z.object({
                            code: z.string(),
                            libelle: z.string(),
                            valide: z.boolean(),
                          }),
                          sexe: z.string(),
                          id: z.number(),
                          valide: z.boolean(),
                          poidsDouble: z.number(),
                          echelon: z.number(),
                        }),
                        libelle: z.string(),
                        id: z.number(),
                        type: z.string(),
                        publicationResultat: z.boolean(),
                      }),
                      z.object({
                        classementBas: z.object({
                          nature: z.string(),
                          libelle: z.string(),
                          serie: z.object({
                            code: z.string(),
                            libelle: z.string(),
                            valide: z.boolean(),
                          }),
                          sexe: z.string(),
                          id: z.number(),
                          valide: z.boolean(),
                          poidsDouble: z.number(),
                          echelon: z.number(),
                        }),
                        rangProgression: z.number(),
                        classementHaut: z.object({
                          nature: z.string(),
                          libelle: z.string(),
                          serie: z.object({
                            code: z.string(),
                            libelle: z.string(),
                            valide: z.boolean(),
                          }),
                          sexe: z.string(),
                          id: z.number(),
                          valide: z.boolean(),
                          poidsDouble: z.number(),
                          echelon: z.number(),
                        }),
                        libelle: z.string(),
                        id: z.number(),
                        type: z.string(),
                        statut: z.object({
                          libelle: z.string(),
                          id: z.number(),
                        }),
                        publicationResultat: z.boolean(),
                      }),
                    ])
                  )
                  .optional(),
                clotureInscriptionSansPreavis: z.boolean(),
                type: z.string(),
                publicationResultat: z.boolean(),
                tarifJeune: z.number(),
                categorieAgeMax: z.object({
                  ageJoueurMin: z.number(),
                  ageMin: z.number(),
                  ageJoueurMax: z.number(),
                  ageRechercheMax: z.number(),
                  categoriesAgeTypePratique: z.array(
                    z.object({
                      createTime: z.string(),
                      id: z.object({
                        typePratique: z.string(),
                        idCategorieAge: z.number(),
                      }),
                    })
                  ),
                  ageMax: z.number(),
                  libelle: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  ageReel: z.boolean(),
                  ageRechercheMin: z.number(),
                  homologable: z.boolean(),
                }),
                id: z.number(),
                natureEpreuve: z.object({
                  code: z.string(),
                  libelle: z.string(),
                  sexe: z.string(),
                  valide: z.boolean(),
                }),
                inscriptionEnLigne: z.boolean(),
                fillesAutorisees: z.boolean(),
                formatMatch: z.object({
                  code: z.string(),
                  classementMax: z.object({
                    nature: z.string(),
                    libelle: z.string(),
                    serie: z.object({
                      code: z.string(),
                      libelle: z.string(),
                      valide: z.boolean(),
                    }),
                    sexe: z.string(),
                    id: z.number(),
                    valide: z.boolean(),
                    poidsDouble: z.number(),
                    echelon: z.number(),
                  }),
                  ageMax: z.number(),
                  nombreSets: z.number(),
                  double: z.boolean(),
                  libelle: z.string(),
                  simple: z.boolean(),
                  valide: z.boolean(),
                  superJeuDecisif: z.boolean(),
                  ageMin: z.number(),
                  coefficient: z.number(),
                  duree: z.number(),
                  classementMin: z.object({
                    nature: z.string(),
                    libelle: z.string(),
                    serie: z.object({
                      code: z.string(),
                      libelle: z.string(),
                      valide: z.boolean(),
                    }),
                    sexe: z.string(),
                    id: z.number(),
                    valide: z.boolean(),
                    poidsDouble: z.number(),
                    echelon: z.number(),
                  }),
                  millesimeDebutValidite: z.number(),
                }),
                tarifAdulte: z.number(),
                dateProgrammation: z.string().optional(),
                classementBas: z.object({
                  nature: z.string(),
                  libelle: z.string(),
                  serie: z.object({
                    code: z.string(),
                    libelle: z.string(),
                    valide: z.boolean(),
                  }),
                  sexe: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  poidsDouble: z.number(),
                  echelon: z.number(),
                }),
                tarifsSpecifiques: z.array(z.unknown()),
                homologuee: z.boolean(),
                dateDebut: z.string(),
                dateFin: z.string(),
                borneAnneesNaissance: z.object({
                  min: z.number(),
                  max: z.number(),
                }),
                open: z.boolean(),
                statut: z.object({ libelle: z.string(), id: z.number() }),
              }),
              z.object({
                inscriptionEnLigneEnCours: z.boolean(),
                categorieAge: z.object({
                  ageJoueurMin: z.number(),
                  ageMin: z.number(),
                  ageJoueurMax: z.number(),
                  ageRechercheMax: z.number(),
                  categoriesAgeTypePratique: z.array(
                    z.object({
                      createTime: z.string(),
                      id: z.object({
                        typePratique: z.string(),
                        idCategorieAge: z.number(),
                      }),
                    })
                  ),
                  ageMax: z.number(),
                  libelle: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  ageReel: z.boolean(),
                  ageRechercheMin: z.number(),
                  homologable: z.boolean(),
                }),
                classementHaut: z.object({
                  nature: z.string(),
                  libelle: z.string(),
                  serie: z.object({
                    code: z.string(),
                    libelle: z.string(),
                    valide: z.boolean(),
                  }),
                  sexe: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  poidsDouble: z.number(),
                  echelon: z.number(),
                }),
                nombreDecoupagesPublies: z.number(),
                libelle: z.string(),
                participationAgeReel: z.boolean(),
                decoupages: z
                  .array(
                    z.object({
                      classementBas: z.object({
                        nature: z.string(),
                        libelle: z.string(),
                        serie: z.object({
                          code: z.string(),
                          libelle: z.string(),
                          valide: z.boolean(),
                        }),
                        sexe: z.string(),
                        id: z.number(),
                        valide: z.boolean(),
                        poidsDouble: z.number(),
                        echelon: z.number(),
                      }),
                      rangProgression: z.number(),
                      classementHaut: z.object({
                        nature: z.string(),
                        libelle: z.string(),
                        serie: z.object({
                          code: z.string(),
                          libelle: z.string(),
                          valide: z.boolean(),
                        }),
                        sexe: z.string(),
                        id: z.number(),
                        valide: z.boolean(),
                        poidsDouble: z.number(),
                        echelon: z.number(),
                      }),
                      libelle: z.string(),
                      id: z.number(),
                      type: z.string(),
                      statut: z.object({ libelle: z.string(), id: z.number() }),
                      publicationResultat: z.boolean(),
                    })
                  )
                  .optional(),
                clotureInscriptionSansPreavis: z.boolean(),
                type: z.string(),
                publicationResultat: z.boolean(),
                tarifJeune: z.number(),
                categorieAgeMax: z.object({
                  ageJoueurMin: z.number(),
                  ageMin: z.number(),
                  ageJoueurMax: z.number(),
                  ageRechercheMax: z.number(),
                  categoriesAgeTypePratique: z.array(
                    z.object({
                      createTime: z.string(),
                      id: z.object({
                        typePratique: z.string(),
                        idCategorieAge: z.number(),
                      }),
                    })
                  ),
                  ageMax: z.number(),
                  libelle: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  ageReel: z.boolean(),
                  ageRechercheMin: z.number(),
                  homologable: z.boolean(),
                }),
                id: z.number(),
                natureEpreuve: z.object({
                  code: z.string(),
                  libelle: z.string(),
                  sexe: z.string(),
                  valide: z.boolean(),
                }),
                inscriptionEnLigne: z.boolean(),
                fillesAutorisees: z.boolean(),
                formatMatch: z.object({
                  code: z.string(),
                  classementMax: z.object({
                    nature: z.string(),
                    libelle: z.string(),
                    serie: z.object({
                      code: z.string(),
                      libelle: z.string(),
                      valide: z.boolean(),
                    }),
                    sexe: z.string(),
                    id: z.number(),
                    valide: z.boolean(),
                    poidsDouble: z.number(),
                    echelon: z.number(),
                  }),
                  ageMax: z.number(),
                  nombreSets: z.number(),
                  double: z.boolean(),
                  libelle: z.string(),
                  simple: z.boolean(),
                  valide: z.boolean(),
                  superJeuDecisif: z.boolean(),
                  ageMin: z.number(),
                  coefficient: z.number(),
                  duree: z.number(),
                  classementMin: z.object({
                    nature: z.string(),
                    libelle: z.string(),
                    serie: z.object({
                      code: z.string(),
                      libelle: z.string(),
                      valide: z.boolean(),
                    }),
                    sexe: z.string(),
                    id: z.number(),
                    valide: z.boolean(),
                    poidsDouble: z.number(),
                    echelon: z.number(),
                  }),
                  millesimeDebutValidite: z.number(),
                }),
                tarifAdulte: z.number(),
                dateProgrammation: z.string().optional(),
                classementBas: z.object({
                  nature: z.string(),
                  libelle: z.string(),
                  serie: z.object({
                    code: z.string(),
                    libelle: z.string(),
                    valide: z.boolean(),
                  }),
                  sexe: z.string(),
                  id: z.number(),
                  valide: z.boolean(),
                  poidsDouble: z.number(),
                  echelon: z.number(),
                }),
                tarifsSpecifiques: z.array(z.unknown()),
                homologuee: z.boolean(),
                dateDebut: z.string(),
                dateFin: z.string(),
                borneAnneesNaissance: z.object({
                  min: z.number(),
                  max: z.number(),
                }),
                open: z.boolean(),
                statut: z.object({ libelle: z.string(), id: z.number() }),
              }),
            ])
          ),
          dateDebut: z.object({
            date: z.string(),
            timezone_type: z.number(),
            timezone: z.string(),
          }),
          serie: z.object({
            code: z.string(),
            libelle: z.string(),
            valide: z.boolean(),
          }),
          dateFin: z.object({
            date: z.string(),
            timezone_type: z.number(),
            timezone: z.string(),
          }),
          dateValidation: z.string(),
          codePostalEngagement: z.string().optional(),
          codeClub: z.string(),
          prixEspece: z.number(),
          isTournoi: z.boolean(),
          natureWithCatAge: z.object({
            SD: z.object({ 200: z.string() }).optional(),
            SM: z.object({ 200: z.string() }).optional(),
          }),
        }),
        favoris: z.string(),
      })
    ),
  }),
  head: z.string(),
  pagination: z.null(),
  settings: z.null(),
});
